# Generated by Django 5.1.2 on 2024-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('c', 'Completed'), ('p', 'Pending')], default='p', max_length=1),
        ),
    ]
